var gamePattern=[];var userClickedPattern=[];var buttonColors=["green","red","yellow","blue"];var keyCount=0;var level=0;$("h1").click(function(){userClickedPattern=[]
    if(keyCount===0){$(".body").removeClass("wrong");keyCount++;level++;$("h1").text("Level "+level);nextSequence()}});$(".cheat").click(function(){var cheatArray=gamePattern.join(", ");$(".cheat").html(cheatArray)});$("#green").on("click",function(){greenPress();$(".body").removeClass("wrong")});$("#red").on("click",function(){redPress();$(".body").removeClass("wrong")});$("#yellow").on("click",function(){yellowPress();$(".body").removeClass("wrong")});$("#blue").on("click",function(){bluePress();$(".body").removeClass("wrong")});function nextSequence(){$(".body").removeClass("wrong");var randomNumber=Math.random();randomNumber=Math.floor(randomNumber*4)
    var randomChosenColour=buttonColors[randomNumber];gamePattern.push(randomChosenColour);if(randomChosenColour==="green"){var audio=new Audio("./sounds/green.mp3");audio.play();$("#green").removeClass("pressAnimate");setTimeout(()=>{$("#green").addClass("pressAnimate")},100)}
    if(randomChosenColour==="red"){var audio=new Audio("./sounds/red.mp3");audio.play();$("#red").removeClass("pressAnimate");setTimeout(()=>{$("#red").addClass("pressAnimate")},100)}
    if(randomChosenColour==="yellow"){var audio=new Audio("./sounds/yellow.mp3");audio.play();$("#yellow").removeClass("pressAnimate");setTimeout(()=>{$("#yellow").addClass("pressAnimate")},100)}
    if(randomChosenColour==="blue"){var audio=new Audio("./sounds/blue.mp3");audio.play();$("#blue").removeClass("pressAnimate");setTimeout(()=>{$("#blue").addClass("pressAnimate")},100)}
    $(".cheat").html("Cheat")}
    function check(){var checker=0;var error=!1;for(var x=0;x<userClickedPattern.length;x++){if(gamePattern[x]!==userClickedPattern[x]){error=!0}
    if(gamePattern[x]===userClickedPattern[x]){checker++}}
    if(error===!0){wrongPress();userClickedPattern=[];keyCount=0;level=0;gamePattern=[];$("h1").text("Click me to try again")}else if(checker===gamePattern.length){level++;$("h1").text("Level "+level);userClickedPattern=[];setTimeout(()=>{nextSequence()},1000)}}
    function greenPress(){var audio=new Audio("./sounds/green.mp3");audio.play();$("#green").removeClass("pressAnimate");setTimeout(()=>{$("#green").addClass("pressAnimate")},100);userClickedPattern.push("green");check()}
    function redPress(){var audio=new Audio("./sounds/red.mp3");audio.play();$("#red").removeClass("pressAnimate");setTimeout(()=>{$("#red").addClass("pressAnimate")},100);userClickedPattern.push("red");check()}
    function yellowPress(){var audio=new Audio("./sounds/yellow.mp3");audio.play();$("#yellow").removeClass("pressAnimate");setTimeout(()=>{$("#yellow").addClass("pressAnimate")},100);userClickedPattern.push("yellow");check()}
    function bluePress(){var audio=new Audio("./sounds/blue.mp3");audio.play();$("#blue").removeClass("pressAnimate");setTimeout(()=>{$("#blue").addClass("pressAnimate")},100);userClickedPattern.push("blue");check()}
    function wrongPress(){var audio=new Audio("./sounds/wrong.mp3");audio.play();$("#yellow,#red,#blue,#green").removeClass("pressAnimate");setTimeout(()=>{$("#yellow,#red,#blue,#green").addClass("pressAnimate")},100);$(".body").removeClass("wrong");setTimeout(()=>{$(".body").addClass("wrong")},200)}